#!/bin/bash

# 🚀 GUÍA PASO A PASO: SUBIR A GITHUB
# ====================================

echo "📋 PASOS PARA SUBIR TU REPOSITORIO A GITHUB"
echo ""
echo "1️⃣  CREAR EL REPOSITORIO EN GITHUB"
echo "   - Ir a: https://github.com/new"
echo "   - Repository name: landing-assets"
echo "   - Description: Assets para landing de Laboratorios Katz"
echo "   - ✅ Marcar como: PUBLIC"
echo "   - ❌ NO inicializar con README (ya lo tenemos)"
echo "   - Hacer click en: 'Create repository'"
echo ""
echo "2️⃣  CONECTAR TU REPOSITORIO LOCAL CON GITHUB"
echo "   Copiar y ejecutar estos comandos:"
echo ""
echo "   cd /tmp/landing-assets"
echo "   git remote add origin https://github.com/santiagochinellato/landing-assets.git"
echo "   git push -u origin main"
echo ""
echo "   ⚠️  GitHub te pedirá autenticación:"
echo "      - Usuario: santiagochinellato"
echo "      - Password: usa un Personal Access Token (NO tu contraseña)"
echo ""
echo "3️⃣  CREAR UN PERSONAL ACCESS TOKEN (si no tenés)"
echo "   - Ir a: https://github.com/settings/tokens"
echo "   - Click en: 'Generate new token' > 'Classic'"
echo "   - Note: 'Landing Assets Upload'"
echo "   - Expiration: 90 days (o lo que prefieras)"
echo "   - Scopes: marcar 'repo' (acceso completo a repositorios)"
echo "   - Click en: 'Generate token'"
echo "   - ⚠️  COPIARLO INMEDIATAMENTE (no lo volverás a ver)"
echo ""
echo "4️⃣  VERIFICAR QUE SE SUBIÓ CORRECTAMENTE"
echo "   - Ir a: https://github.com/santiagochinellato/landing-assets"
echo "   - Deberías ver: README.md, public/, compress-video.sh, etc."
echo "   - Navegar a: public/videos/vertical.mp4"
echo ""
echo "5️⃣  PROBAR LA URL DE JSDELIVR (esperar 1-2 minutos)"
echo "   Abrir en el navegador:"
echo "   https://cdn.jsdelivr.net/gh/santiagochinellato/landing-assets@main/public/videos/vertical.mp4"
echo ""
echo "✅ LISTO! Tu video está en la CDN global"
echo ""
